name: Build font

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: sudo apt-get install ttfautohint -y

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - run: npm i
    - run: npm run build -- contents::iosevka-custom

    - name: Upload the font artifact
      uses: actions/upload-artifact@v2
      with:
        name: iosevka-custom-font
        path: ./dist/
